services:
  deepsproxy-x11:
    container_name: deepsproxy-x11
    build: .
    ports:
      - 5901:5901 ## vnc
      - 8080:8080 ## novnc
      - 3000:3000 ## app-proxy
    environment:
      - VNC_PASSWORD=123456
    volumes:
      - vnc-home:/home/vncuser
    shm_size: '256mb'
    networks:
      net:
        ipv4_address: 172.15.0.18
    logging:
      options:
        max-size: 100M
    #entrypoint: sleep 1000000       

volumes:
  vnc-home:

networks:
  net:
    external: true