[supervisord]  
nodaemon=true  
logfile=/dev/null  
logfile_maxbytes=0
  
[program:vncserver]  
priority=10  
command=vncserver -localhost no -geometry 1280x720 -depth 24 :1 -fg
startsecs=1  
autorestart=false  
startretries=1  
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
  
[program:websockify]  
priority=20
command=websockify --web /usr/share/novnc 8080 localhost:5901  
startsecs=0  
autorestart=false  
startretries=2  
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true  
  
[program:app]  
priority=30
command=node /home/vncuser/app/dist/index.js  
startsecs=0  
autorestart=false  
startretries=2  
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true